### ISSUE TITLE
Pypi Wrong Package

### ISSUE THREAD

**Issue by edwinlunando** [PetrDlouhy/django-related-admin#1]
I tried to install this package from pip, but it installed another package. I think it installed this package https://pypi.python.org/pypi/django-related-admin/1.0.0 instead. 

Also, how about add support for generating link(anchor) on the related model, instead of text.

**Comment by PetrDlouhy** [comment]
Is this still relevant? The new version `0.4.0` is on PyPI.

Can you please describe the link(anchor) functionality a bit more in detail in separate issue?
