### ISSUE TITLE
What is the license for django-related-admin?

### ISSUE THREAD

**Issue by aboisvert** [PetrDlouhy/django-related-admin#14]
I could not find a definite answer for this ... there isn't a license mentioned in the README and no LICENSE file at the root.  Source files don't mention a license either (as far as I could tell.).

Could somebody authoritatively state which license this project is distributed under?

thank you!

**Comment by PetrDlouhy** [comment]
@aboisvert Hi,

thank you for pointing that out. I probably forgot to include the license. Do you think, that GPLv3 is good choice?

@artscoop, @kgrandis, @theY4Kman, @leibowitz Are you OK with GPLv3?

**Comment by PetrDlouhy** [comment]
I remembered, that I based this on this snippet: https://djangosnippets.org/snippets/2996/
That is the reason, that I did not include the license, because I never did get answer about the license there.
@kpacn Is that You who originated the snippet? Do you agree with GPLv3, or suggest some other license?

**Comment by leibowitz** [comment]
> ### What license are the code snippets under?
> No particular license; everyone who signs up agrees to the Terms of Service which simply state that code they post can be used by anyone in any way.

Source: https://djangosnippets.org/about/faq/

> By creating an account here you agree to three things:
> 
> 1. That you will only post code which you wrote yourself and that you have the legal right to release under these terms.
> 
> 2. That you grant any third party who sees the code you post a royalty-free, non-exclusive license to copy and distribute that code and to make and distribute derivative works based on that code. You may include license terms in snippets you post, if you wish to use a particular license (such as the BSD license or GNU GPL), but that license must permit royalty-free copying, distribution and modification of the code to which it is applied.
> 3. That if you post code of which you are not the author or for which you do not have the legal right to distribute according to these terms, you will indemnify and hold harmless the operators of this site and any third parties who are exposed to liability as a result of your actions.
> 
> If you can't legally agree to these terms, or don't want to, you cannot create an account here.

Source: https://djangosnippets.org/about/tos/

**Comment by leibowitz** [comment]
I'm not a lawyer, but it seems you can pick whichever license you want based on that.

I would opt for GPL or MIT. As I understand MIT is more permissive (can be used even without distributing the source)

Some documentation on licenses that can help you make an informed decision:
https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633
https://choosealicense.com/
https://exygy.com/blog/which-license-should-i-use-mit-vs-apache-vs-gpl/

**Comment by PetrDlouhy** [comment]
I taught a bit about it, and I think, that the BSD license would be best, because it would allow code exchange with upstream Django without any question.

**Comment by aboisvert** [comment]
We are using django-related-admin in a commercial application.  If the license were to be determined to be GPL, we would have to migrate away from this project :(

**Comment by PetrDlouhy** [comment]
@aboisvert What exactly does the BSD license prohibit in your commercial application?
The BSD license should be (much more) permissive, than GPL.

I personally am not against any license or multiple licenses, if that makes sense. If you suggest better solution, I can go with it.

BTW I think, that most open-source licenses affect mostly distribution of the software, not using it. And I hope, that deployment of the software on server using tools like `pip` doesn't count as distribution.

**Comment by leibowitz** [comment]
BSD is MIT-like, in term of commercial use. Therefore it is one of the most permissive option. It looks like @aboisvert was referring to GPL, rather than BSD.

Hope that clears the confusion

**Comment by aboisvert** [comment]
Yes, I was referring to GPL.   BSD would be great.

**Comment by theY4Kman** [comment]
BSD or MIT sounds tasty to me

**Comment by PetrDlouhy** [comment]
This has been already solved, closing.
