### ISSUE TITLE
Boolean

### ISSUE THREAD

**Issue by ricardobfreitas** [PetrDlouhy/django-related-admin#2]
Boolean attributes appears as "True" os "False" instead of the "check icon" in Admin. Is it possible to show the "check icon" using the django-related-admin? How?
Thanks! (Sorry for the english!)

**Comment by PetrDlouhy** [comment]
This is now possible to achieve by following code in `ModelAdmin`:
```
user__active = getter_for_related_field('user__active', boolean=True)
```
