### ISSUE TITLE
getter_for_related_field not working in Django 1.9

### ISSUE THREAD

**Issue by shnako** [PetrDlouhy/django-related-admin#3]
Here's a simplified example:

```
class LegalAdmin(RelatedFieldAdmin):
    ordering = ('user__first_name',
                )
    list_display = ('user__first_name',
                    'legal_name',
                    'user__is_active'
                    )

    user__first_name = getter_for_related_field('user__first_name', short_description='Name')
```

This results in the following (note it's still showing as FIRST NAME although it should be NAME):

![2016-05-28 14_03_26-selecteaza salon pentru schimbare _ administrare site django](https://cloud.githubusercontent.com/assets/4254710/15627468/14a31be8-24dd-11e6-863d-c3551505d0b8.png)

**Comment by PetrDlouhy** [comment]
This is fixed in version 0.4.0
