### ISSUE TITLE
break list_filter

### ISSUE THREAD

**Issue by flamby** [PetrDlouhy/django-related-admin#9]
Hi,
Thanks for this app, it works like a charm and permitted me to remove lots of boilerplate code of my admin files.

Nevertheless, I tried to add one of those fields in my list_filter and it seems it does not like that ;-)

admin.E116) The value of 'list_filter[2]' refers to 'fmt_forecast_steps', which does not refer to a Field

Is it a known issue and easy fixable?

TIA

**Comment by PetrDlouhy** [comment]
@flamby I don't know what do you exactly mean. I would need some example of your code. But `django-related-admin` doesn't do anything with `list_filter`, it is done by Django itself. The syntax is similar, but you can't create `list_filter` from class methods, which could be done with `list_display` thanks to `django-related-admin`.

**Comment by flamby** [comment]
thanks for the clarification.
